### ISSUE TITLE
Grid next nav takes extra click w/ custom start date

### ISSUE THREAD

**Issue by pderksen** [moonstonemedia/Simple-Calendar#106]
Add a custom start date in grid view.

Clicking on next shows animation but doesn't nav to new month. Clicking a 2nd time does.

Ref #103

**Comment by pderksen** [comment]
Screencast: http://screencast.com/t/xl1eVaXCR

**Comment by nickyoung87** [comment]
@pderksen I have still not been able to reproduce this.

- Do you think it is an OS + browser issue?
- Maybe it could be a plugin conflict?
- Does this happen right after you clear the cache on the calendar and then once refreshed again it works?

**Comment by pderksen** [comment]
@nickyoung87 Don't sweat it for 3.0.13 if you can't reproduce. Could be a minor conflict. We can test later.

**Comment by nickyoung87** [comment]
@pderksen When you get a chance can you test this (since I couldn't reproduce) with the `release/3.0.14` branch?

**Comment by pderksen** [comment]
@nickyoung87 Assigning back as you are now able to repeat. If it's a weird JS event issue that you get stuck on send over to me.

**Comment by nickyoung87** [comment]
@pderksen Ok so this came down to a timezone thing. Since it is in JS and it will pick up the timezone from the user I added 1 day to the time it uses for the paging. It seems to work fine for me and I don't think there will be issues with it for others. It only affects the paging, not the events or anything else and the way it works should still be ok. It doesn;'t matter if we use the 1st, 17th, 23rd, etc day because it resets it to a specific day and calculates from there - so adding 1 day should not pose to be a problem.

Of course if there is a problem then I know exactly where it is and we can easily revert if needed after the update goes live and if people bring up an issue around it - but I don't think that will be the case.

**Comment by pderksen** [comment]
@nickyoung87 Sounds good.
