### ISSUE TITLE
Event detail bubble is not displayed

### ISSUE THREAD

**Issue by AlbertoGuerreroMartin** [moonstonemedia/Simple-Calendar#174]
I currently have WordPress 4.5.2 version installed, with [Pytheas](http://wpexplorer-demos.com/pytheas/) theme (1.4 version), and apparently for no reason event detail's bubble is not appearing. I've tried with both click and hover options, with no success.

Could you please check it? Thanks!!

**Comment by nickyoung87** [comment]
Sorry about the issue you're experiencing.

If you recently upgraded to WordPress 4.5, there is a common issue that has cropped up for some folks affecting many plugins and themes stemming from other plugins and themes.

Short version: Update all your plugins and themes to the latest versions by their vendors. 

<a href="https://wordpress.org/support/topic/read-this-first-wordpress-45-master-list?replies=7#post-8271654">Read the detailed version here</a> if you need a technical explanation in order to troubleshoot this particular conflict further.

Finally, if your issue is still not resolved or is not related to an update to WordPress 4.5, we still recommend the best way to go about fixing this is testing for theme or plugin conflicts.

http://docs.simplecalendar.io/troubleshooting-theme-plugin-widget-conflicts/

Thanks!

**Comment by nickyoung87** [comment]
@AlbertoGuerreroMartin Have you gotten a chance to run through the troubleshooting above?

**Comment by AlbertoGuerreroMartin** [comment]
@nickyoung87 yes, the issue was related to the version of Pytheas theme, I just updated it and everything is working fine now.

Thanks for your help!

**Comment by nickyoung87** [comment]
Awesome glad to hear you got it resolved. Thanks for letting us know.
